### ISSUE TITLE
support controlnet or inpaint

### ISSUE THREAD

**Issue by whmc76** [florestefano1975/ComfyUI-HiDiffusion#5]
could we adjust the node like a model patch?
that will be great to apply hidiffusion in many workflows

![image](https://github.com/florestefano1975/ComfyUI-HiDiffusion/assets/129386342/06342cb0-05af-4a29-8fbe-c710dc912556)

**Comment by florestefano1975** [comment]
Yes, if I have time I will also look for a similar solution.
